### ISSUE TITLE
The need of 4 different bitrates and psnr

### ISSUE THREAD

**Issue by sdancer75** [tbr/bjontegaard_etro#2]
Why do we need at least 4 samples of bitrate and PSNR for curve1 and curve2 to take a result ie `=BDSNR(A5:A8,B5:B8,C5:C8,D5:D8)` and `=BDBR(A5:A8,B5:B8,C5:C8,D5:D8)` ?

 It returns an error if I use just one bitrate and PSNR sample for each curve ie
a)  `=BDSNR(A5:A5,B5:B5,C5:C5,D5:D5)` and
b) `=BDBR(A5:A5,B5:B5,C5:C5,D5:D5)`

I think it should work just fine with just one sample of each curve.

**Comment by tbr** [comment]
If you only have one sample, then how can it calculate a curve? With two samples it can calculate a line and three would be a minimum for a "curve". If you have one sample, then just calculate PSNR. The whole point of Bjontegaard delta is that it represents a measure of the surface area "between" two curves.

This project is a compliant implementation of the Bjontegaard metric as specified by the original author (see references [1] and [2]). Then it is extended to allow more than 4 samples (but less makes really no sense).

**Comment by sdancer75** [comment]
Yes, thank you, my 1st thought, was just to compare the two values (PRNR/BitRate) of two different encoding settings without any curves, and evaluate the results, but after reading more about the bjontegaard metric, I understand that it needs at least 4 samples from each encoder to receive safe results.

Anyway, thank you for the time to explain this.

Best Regards,
